import { useState } from 'react';
import { Target, BookOpen, CheckCircle, Circle, ChevronRight, Star, TrendingUp, Calendar } from 'lucide-react';
import { practiceCategories, recommendationRules } from '../data/practiceQuestions';

const skillLevels = ['Beginner', 'Intermediate', 'Advanced'];
const areaMap = {
  'Quantitative Aptitude':               'quantitative',
  'Logical Reasoning':                   'logical',
  'Verbal Ability':                      'verbal',
  'Programming Fundamentals':            'programming',
  'Data Structures and Algorithms':      'dsa',
  'Technical Interview Preparation':     'dsa',
};

export default function PlacementPreparation({ onStartPractice }) {
  const [skill,    setSkill]    = useState('');
  const [area,     setArea]     = useState('');
  const [progress, setProgress] = useState({});

  const ruleKey  = skill.toLowerCase();
  const areaKey  = area ? (areaMap[area] || 'quantitative') : null;
  const rule     = ruleKey && areaKey ? recommendationRules[ruleKey]?.[areaKey] : null;

  function toggleTopic(topic) {
    setProgress(p => ({ ...p, [topic]: !p[topic] }));
  }

  const completedCount = rule ? rule.topics.filter(t => progress[t]).length : 0;
  const totalCount     = rule ? rule.topics.length : 0;

  return (
    <div id="placement" className="space-y-6">
      {/* Disclaimer */}
      <div className="p-4 bg-violet-50 border border-violet-200 rounded-2xl">
        <p className="text-sm text-violet-800 font-medium mb-1">📌 About This Section</p>
        <p className="text-xs text-violet-700 leading-relaxed">
          Academic grades are one indicator of performance but should not be used alone to determine coding or aptitude ability.
          Consistent practice, problem-solving skills and communication are equally important for placement success.
          The recommendations below are predefined based on the skill level you select — not generated by AI.
        </p>
      </div>

      {/* Selectors */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div>
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-3">Select Your Skill Level</p>
          <div className="flex flex-col gap-2">
            {skillLevels.map(s => (
              <button
                key={s}
                onClick={() => { setSkill(s); setProgress({}); }}
                className={`flex items-center gap-3 px-4 py-3 rounded-xl border text-sm font-medium transition text-left ${
                  skill === s
                    ? 'bg-ktu-navy text-white border-ktu-navy shadow-sm'
                    : 'bg-white text-slate-600 border-slate-200 hover:border-navy-300 hover:bg-navy-50'
                }`}
              >
                <Star size={15} className={skill === s ? 'text-yellow-300' : 'text-slate-300'} />
                {s}
              </button>
            ))}
          </div>
        </div>

        <div>
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-3">Choose Preparation Area</p>
          <div className="flex flex-col gap-2">
            {Object.keys(areaMap).map(a => (
              <button
                key={a}
                onClick={() => { setArea(a); setProgress({}); }}
                className={`flex items-center gap-2.5 px-4 py-3 rounded-xl border text-sm font-medium transition text-left ${
                  area === a
                    ? 'bg-ktu-violet text-white border-ktu-violet shadow-sm'
                    : 'bg-white text-slate-600 border-slate-200 hover:border-violet-300 hover:bg-violet-50'
                }`}
              >
                <BookOpen size={14} className={area === a ? 'text-white/80' : 'text-slate-400'} />
                {a}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Plan */}
      {rule && (
        <div className="space-y-4 animate-in fade-in">
          {/* Progress bar */}
          <div className="card">
            <div className="flex items-center justify-between mb-2">
              <p className="text-sm font-bold text-ktu-blue">
                {skill} · {area}
              </p>
              <p className="text-xs text-slate-400">
                {completedCount} / {totalCount} topics
              </p>
            </div>
            <div className="w-full bg-slate-100 rounded-full h-2 mb-4">
              <div
                className="h-2 rounded-full bg-gradient-to-r from-ktu-violet to-ktu-cyan transition-all duration-500"
                style={{ width: `${totalCount ? (completedCount / totalCount) * 100 : 0}%` }}
              />
            </div>

            {/* Recommended Topics */}
            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-3">Recommended Topics</p>
            <div className="space-y-2">
              {rule.topics.map(topic => (
                <button
                  key={topic}
                  onClick={() => toggleTopic(topic)}
                  className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl border text-sm text-left transition ${
                    progress[topic]
                      ? 'bg-emerald-50 border-emerald-200 text-emerald-700'
                      : 'bg-white border-slate-100 text-slate-700 hover:border-slate-200 hover:bg-slate-50'
                  }`}
                >
                  {progress[topic]
                    ? <CheckCircle size={16} className="text-emerald-500 shrink-0" />
                    : <Circle size={16} className="text-slate-300 shrink-0" />
                  }
                  <span className={progress[topic] ? 'line-through text-emerald-600' : ''}>{topic}</span>
                  {!progress[topic] && <ChevronRight size={14} className="text-slate-300 ml-auto" />}
                </button>
              ))}
            </div>
          </div>

          {/* Weekly Plan */}
          <div className="card">
            <div className="flex items-center gap-2 mb-3">
              <Calendar size={16} className="text-ktu-violet" />
              <p className="text-sm font-bold text-ktu-blue">Weekly Study Plan</p>
            </div>
            <div className="space-y-2">
              {rule.weeklyPlan.map((week, i) => (
                <div key={i} className="flex items-start gap-3 p-3 bg-slate-50 rounded-xl">
                  <span className="w-6 h-6 rounded-full bg-ktu-violet text-white text-xs font-bold flex items-center justify-center shrink-0">
                    {i + 1}
                  </span>
                  <p className="text-xs text-slate-600 leading-relaxed">{week}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Goals */}
          <div className="card">
            <div className="flex items-center gap-2 mb-3">
              <Target size={16} className="text-ktu-cyan" />
              <p className="text-sm font-bold text-ktu-blue">Learning Goals</p>
            </div>
            <ul className="space-y-2">
              {rule.goals.map((goal, i) => (
                <li key={i} className="flex items-start gap-2.5 text-sm text-slate-600">
                  <TrendingUp size={14} className="text-ktu-cyan shrink-0 mt-0.5" />
                  {goal}
                </li>
              ))}
            </ul>
          </div>

          {/* CTA */}
          <button
            onClick={() => onStartPractice(areaKey, skill.toLowerCase())}
            className="btn-accent w-full justify-center py-3 text-sm"
          >
            <BookOpen size={16} /> Start Practising — {area}
          </button>
        </div>
      )}

      {!rule && (
        <div className="text-center py-12 bg-slate-50 rounded-2xl border border-slate-100">
          <Target size={32} className="text-slate-300 mx-auto mb-3" />
          <p className="text-sm font-medium text-slate-500">Select a skill level and preparation area</p>
          <p className="text-xs text-slate-400 mt-1">Your personalised study plan will appear here</p>
        </div>
      )}
    </div>
  );
}
